dist: xenial
language: go

branches:
  only:
  - master

git:
  depth: false

jobs:
  include:
  - env: CMD="make validate"
  - env: CMD="make deploy deploytool=helm globalnet=true"
  - env: CMD="make deploy deploytool=operator" DEPLOY=true

install:
  - sudo apt-get install curl moreutils # make ts available
  - curl https://codeload.github.com/kward/shflags/tar.gz/v1.2.3 | tar -xzf - && sudo mv shflags-1.2.3 /usr/share/shflags

services:
  - docker

script:
  - set -o pipefail;
    $CMD 2>&1 | ts '[%H:%M:%.S]' -s

after_success:
 -  echo "Testing clean up";
    set -o pipefail;
    make cleanup 2>&1 | ts '[%H:%M:%.S]' -s

deploy:
  - provider: script
    script: make dapper-image release images="shipyard-dapper-base" dapper_image_flags="--nocache"
    on:
      branch: master
      condition: $DEPLOY = true
  - provider: script
    script: make dapper-image release image_tag=$TRAVIS_TAG images="shipyard-dapper-base" dapper_image_flags="--nocache"
    on:
      tags: true
      condition: $DEPLOY = true
