dist: xenial
language: go

branches:
  only:
  - master

git:
  depth: false

jobs:
  include:
  - env: CMD="make validate"
  - env: CMD="make deploy"
         CLUSTERS_ARGS="--globalnet"
         DEPLOY_ARGS="${CLUSTERS_ARGS} --deploytool helm"
  - env: CMD="make deploy"
         RELEASE=true

services:
  - docker

addons:
  apt:
    packages:
      - curl
      - moreutils # make ts available

script:
  - set -o pipefail;
    $CMD 2>&1 | ts '[%H:%M:%.S]' -s

after_success:
 -  echo "Testing clean up";
    set -o pipefail;
    make cleanup 2>&1 | ts '[%H:%M:%.S]' -s

after_failure:
  - if [[ $CMD =~ 'deploy' ]]; then
        make post-mortem;
    fi

deploy:
  - provider: script
    script: make nettest dapper-image dapper_image_flags="--nocache" release RELEASE_ARGS="shipyard-dapper-base nettest"
    on:
      branch: master
      condition: $RELEASE = true
  - provider: script
    script: make nettest dapper-image dapper_image_flags="--nocache" release RELEASE_ARGS="--tag $TRAVIS_TAG shipyard-dapper-base nettest"
    on:
      tags: true
      condition: $RELEASE = true
