dist: xenial
language: go

branches:
  only:
  - master

git:
  depth: false

jobs:
  include:
  - env: CMD="make validate"
  - env: CMD="make deploy deploytool=helm globalnet=true"
  - env: CMD="make deploy deploytool=operator" DEPLOY=true
  - env: CMD="make deploy cable_driver=wireguard"

install:
  - sudo apt-get install curl moreutils # make ts available
  - curl https://codeload.github.com/kward/shflags/tar.gz/v1.2.3 | tar -xzf - && sudo mv shflags-1.2.3 /usr/share/shflags
  - sudo add-apt-repository -y ppa:wireguard/wireguard # add WireGuard support
  - sudo apt-get update
  - sudo apt-get install linux-headers-`uname -r` wireguard -y
  - sudo modprobe wireguard

services:
  - docker

script:
  - set -o pipefail;
    $CMD 2>&1 | ts '[%H:%M:%.S]' -s

after_success:
 -  echo "Testing clean up";
    set -o pipefail;
    make cleanup 2>&1 | ts '[%H:%M:%.S]' -s

deploy:
  - provider: script
    script: make dapper-image dapper_image_flags="--nocache" release release_images="shipyard-dapper-base"
    on:
      branch: master
      condition: $DEPLOY = true
  - provider: script
    script: make dapper-image dapper_image_flags="--nocache" release release_images="shipyard-dapper-base" release_tag="$TRAVIS_TAG"
    on:
      tags: true
      condition: $DEPLOY = true
