---
name: Multi-arch Builds

on:
  pull_request:

permissions: {}

env:
  DEBUG_PRINT: true
jobs:
  check-multiarch:
    name: Check the multi-arch builds
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Set up QEMU (to support building on non-native architectures)
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
      - name: Set up buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb
      - name: Build the multi-arch images
        run: make multiarch-images
      - name: Check that we actually build multi-arch images
        run: bash -c '[ "$(echo package/*.tar)" != "package/*.tar" ]'
