---
name: Periodic

on:
  schedule:
    - cron: "0 0 * * 0"

permissions: {}

jobs:
  markdown-link-check-periodic:
    name: Markdown Links (all files)
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Run markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@4d97ad89bbb0de4be573a9d7a2fc0ce900afc519
        with:
          config-file: ".markdownlinkcheck.json"

      - name: Raise an Issue to report broken links
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f
        with:
          title: Broken link detected by CI
          content-filepath: .github/ISSUE_TEMPLATE/broken-link.md
          labels: automated, broken link

  go-mod-outdated-periodic:
    name: Outdated Dependencies
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [
          'admiral', 'cloud-prepare', 'coastguard', 'lighthouse', 'shipyard',
          'subctl', 'submariner-bot', 'submariner', 'submariner-operator'
        ]
    steps:
      - name: Check out the Shipyard repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Build go-mod-outdated
        run: go build -o bin/go-mod-outdated github.com/psampaz/go-mod-outdated

      - name: Check out the ${{ matrix.project }} repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          repository: submariner-io/${{ matrix.project }}
          path: ${{ matrix.project }}

      - name: Check for updates
        run: (cd ${{ matrix.project }}; go list -u -m -json all) | bin/go-mod-outdated -direct -update
