---
name: Shared Scripts

on:
  pull_request:

jobs:
  clusters:
    name: Clusters
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Deploy clusters
        env:
          CLUSTERS_ARGS: --timeout 1m
        run: make clusters

      - name: Post mortem
        if: failure()
        uses: ./gh-actions/post-mortem

      - name: Clean up clusters
        run: make clean-clusters

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Test the compile.sh script
        run: make vendor/modules.txt script-test SCRIPT_TEST_ARGS="test/scripts/compile/test.sh"

  deploy:
    name: Deploy
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', 'globalnet']
        deploytool: ['operator', 'helm']
        lighthouse: ['']
        ovn: ['']
        include:
          - ovn: ovn
          - deploytool: operator
            lighthouse: lighthouse
          - deploytool: helm
            lighthouse: lighthouse
    steps:
      - name: Reclaim space on GHA host (if the job needs it)
        if: ${{ matrix.ovn != '' }}
        run: rm -rf /usr/share/dotnet

      - name: Check out the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          submodules: true

      - name: Fetch all git tags
        run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Deploy clusters and Submariner
        env:
          CLUSTERS_ARGS: --timeout 1m
          DEPLOY_ARGS: --timeout 2m
        run: make deploy using="${{ matrix.globalnet }} ${{ matrix.deploytool }} ${{ matrix.lighthouse }} ${{ matrix.ovn }}"

      - name: Post mortem
        if: failure()
        uses: ./gh-actions/post-mortem

      - name: Clean up deployment
        run: make clean-clusters

  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Run E2E deployment and tests
        run: make e2e

      - name: Post mortem
        if: failure()
        uses: ./gh-actions/post-mortem

  post_mortem:
    name: Post Mortem
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Deploy some clusters
        run: make clusters

      - name: Test the post_mortem.sh script
        run: make script-test SCRIPT_TEST_ARGS="test/scripts/post_mortem/test.sh"
