---
name: Shared Scripts

on:
  pull_request:

permissions: {}

env:
  DEBUG_PRINT: true
jobs:
  clusters:
    name: Clusters
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Deploy clusters
        env:
          TIMEOUT: 1m
        run: make clusters

      - name: Post mortem
        if: failure()
        uses: ./gh-actions/post-mortem

      - name: Clean up clusters
        run: make clean-clusters

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Test the compile.sh script
        run: make vendor/modules.txt script-test SCRIPT_TEST_ARGS="test/scripts/compile/test.sh"

  deploy:
    name: Deploy
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', 'globalnet']
        deploytool: ['operator', 'helm']
        extra-toggles: ['']
        include:
          - extra-toggles: air-gap
          - extra-toggles: air-gap
            globalnet: globalnet
          - extra-toggles: air-gap
            lighthouse: lighthouse
          - extra-toggles: air-gap
            ovn: ovn
          - extra-toggles: ovn
          - deploytool: operator
            extra-toggles: lighthouse
          - deploytool: helm
            extra-toggles: lighthouse
          - extra-toggles: load-balancer
          - extra-toggles: prometheus
    steps:
      - name: Reclaim space on GHA host (if the job needs it)
        if: ${{ matrix.ovn != '' }}
        run: rm -rf /usr/share/dotnet

      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          submodules: true

      - name: Fetch all git tags
        run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Deploy clusters and Submariner
        env:
          TIMEOUT: 1m
        run: make deploy using="${{ matrix.globalnet }} ${{ matrix.deploytool }} ${{ matrix.extra-toggles }}"

      - name: Post mortem
        if: failure()
        uses: ./gh-actions/post-mortem

      - name: Clean up deployment
        run: make clean-clusters

  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Run E2E deployment and tests
        run: make e2e

      - name: Post mortem
        if: failure()
        uses: ./gh-actions/post-mortem

  post_mortem:
    name: Post Mortem
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Deploy some clusters
        run: make clusters

      - name: Test the post_mortem.sh script
        run: make script-test SCRIPT_TEST_ARGS="test/scripts/post_mortem/test.sh"

  verify_gateways:
    name: Verify gateways
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Deploy clusters and test cloud-prepare
        run: make script-test SCRIPT_TEST_ARGS="test/scripts/cloud-prepare/test.sh"

      - name: Clean up deployment
        run: make clean-clusters
