---
name: Shared Scripts

on:
  pull_request:

jobs:
  clusters:
    name: Clusters
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Deploy clusters
        env:
          CLUSTERS_ARGS: --timeout 1m
        run: make clusters

      - name: Post mortem
        if: failure()
        run: make post-mortem

      - name: Clean up clusters
        run: make cleanup

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Test the compile.sh script
        run: |
          make images .dapper
          ./.dapper -m bind test/scripts/compile/test.sh

  deploy:
    name: Deploy
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', 'globalnet']
        deploytool: ['operator', 'helm']
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Deploy clusters and Submariner
        env:
          CLUSTERS_ARGS: --timeout 1m
          DEPLOY_ARGS: --timeout 2m
        run: make deploy using="${{ matrix.globalnet }} ${{ matrix.deploytool }}"

      - name: Post mortem
        if: failure()
        run: make post-mortem

      - name: Clean up deployment
        run: make cleanup

  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run E2E deployment and tests
        run: make e2e using=ovn

      - name: Post mortem
        if: failure()
        run: make post-mortem

  post_mortem:
    name: Post Mortem
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Test the post_mortem.sh script
        run: |
          make clusters
          ./.dapper -m bind test/scripts/post_mortem/test.sh
