---
name: Unit Test Validation

on:
  pull_request:

permissions: {}

jobs:
  check-unit-tests-fail:
    name: 'Check that unit test failures are detected'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Run unit which is expected to fail
        run: sh -c '! make unit'
