---
name: Upgrade

on:
  pull_request:
    branches: [release-0.14]

permissions: {}

jobs:
  upgrade-e2e:
    name: Latest Release to Latest Version
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Install an old cluster, upgrade it and check it
        uses: ./gh-actions/upgrade-e2e

      - name: Post Mortem
        if: failure()
        uses: ./gh-actions/post-mortem
