on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v**'

name: Validations
jobs:
  validate:
    name: Validating
    strategy:
      fail-fast: false
      matrix:
        command: ['shellcheck', 'validate']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: make ${{ matrix.command }}
